export const wmo-es={0: 'Cielo despejado';
1: 'Mayormente despejado, parcialmente nublado y cubierto';
2: 'Mayormente despejado, parcialmente nublado y cubierto';
3: 'Mayormente despejado, parcialmente nublado y cubierto';
45: 'Niebla y depósito de niebla de escarcha';
48: 'Niebla y depósito de niebla de escarcha';
51: 'Llovizna: Intensidad ligera, moderada y densa';
53 'Llovizna: Intensidad ligera, moderada y densa';
55: 'Llovizna: Intensidad ligera, moderada y densa';
56: 'Llovizna helada: Intensidad ligera y densa';
57: 'Llovizna helada: Intensidad ligera y densa';
61: 'Lluvias: Intensidad leve, moderada y fuerte';
63: 'Lluvias: Intensidad leve, moderada y fuerte';
65: 'Lluvias: Intensidad leve, moderada y fuerte';
66: 'Lluvia helada: Intensidad ligera y fuerte';
67: 'Lluvia helada: Intensidad ligera y fuerte';
71: 'Caída de nieve: intensidad leve, moderada y fuerte';
73: 'Caída de nieve: intensidad leve, moderada y fuerte';
75: 'Caída de nieve: intensidad leve, moderada y fuerte';
77: 'Granos de nieve';
80: 'Lluvias: leves, moderadas y violentas';
81: 'Lluvias: leves, moderadas y violentas';
82: 'Lluvias: leves, moderadas y violentas';
85: 'Nevadas ligeras e intensas';
86: 'Nevadas ligeras e intensas';
95: 'Tormenta: Leve o moderada';
96: 'Tormenta con granizo leve y fuerte';
99: 'Tormenta con granizo leve y fuerte';
}